[package]
name = "ckb-script"
version = "0.40.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
description = "CKB component to run the type/lock scripts."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[features]
default = ["logging"]

asm = ["ckb-vm/asm"]
detect-asm = ["ckb-vm/detect-asm"]
logging = ["ckb-logger"]

[dependencies]
ckb-traits = { path = "../traits", version = "= 0.40.0" }
byteorder = "1.3.1"
ckb-types = {path = "../util/types", version = "= 0.40.0"}
ckb-hash = {path = "../util/hash", version = "= 0.40.0"}
ckb-vm = { git = "https://github.com/nervosnetwork/ckb-vm", rev = "8b3f65d", default-features = false }
faster-hex = "0.4"
ckb-logger = { path = "../util/logger", version = "= 0.40.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
ckb-error = { path = "../error", version = "= 0.40.0" }
ckb-chain-spec = { path = "../spec", version = "= 0.40.0" }
goblin = "0.2"
ckb-vm-definitions = "0.19.3"

[dev-dependencies]
proptest = "0.9"
ckb-db = { path = "../db", version = "= 0.40.0" }
ckb-store = { path = "../store", version = "= 0.40.0" }
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.40.0" }
tiny-keccak = "2.0"
ckb-crypto = { path = "../util/crypto", version = "= 0.40.0" }
ckb-db-schema = { path = "../db-schema", version = "= 0.40.0" }
