name: No Compile Checks

on:
  repository_dispatch:
    types: [ no-compile-checks ]

jobs:

  bootstrap:
    name: Bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              state: 'pending',
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: '${{ github.workflow }}',
              sha: '${{ github.event.client_payload.github.sha }}',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

  rustfmt:
    name: Rustfmt
    needs: [ bootstrap ]
    runs-on: ${{ github.event.client_payload.env.linux_os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.github.sha }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ github.event.client_payload.env.rust_toolchain }}
          components: rustfmt
      - run: make fmt

  check-style:
    name: Check Coding Style
    needs: [ bootstrap ]
    runs-on: ${{ github.event.client_payload.env.linux_os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.github.sha }}
      - run: |
          make check-cargotoml
          make check-whitespaces
          devtools/ci/check-cyclic-dependencies.py

  finally:
    name: Finally
    needs: [ rustfmt, check-style ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - if: contains(join(needs.*.result, ';'), 'failure') || contains(join(needs.*.result, ';'), 'cancelled')
        run: exit 1
      - uses: actions/github-script@v4
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              state: '${{ job.status }}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              context: '${{ github.workflow }}',
              sha: '${{ github.event.client_payload.github.sha }}',
              target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

  trigger-next-checks:
    name: Trigger Next Checks
    needs: [ finally ]
    if: |
      ${{
        github.event.client_payload.github.event_name == 'pull_request'
        || github.event.client_payload.github.ref == 'refs/heads/develop'
        || github.event.client_payload.github.ref == 'refs/heads/master'
        || github.event.client_payload.github.ref == 'refs/heads/trying'
        || github.event.client_payload.github.ref == 'refs/heads/staging'
        || github.event.client_payload.github.ref == 'refs/heads/staging2'
        || startsWith(github.event.client_payload.github.ref, 'refs/heads/rc/')
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: basic-checks
          client-payload: ${{ toJSON(github.event.client_payload) }}
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build-checks
          client-payload: ${{ toJSON(github.event.client_payload) }}
